FROM registry.fedoraproject.org/fedora:33

RUN dnf -y update fedora-gpg-keys && \
    dnf -y install python3-jinja2 python3-yaml git && \
    dnf clean all \
    dnf install python3-pip
    
workdir /workspace

RUN pip install -U pytest

CMD ["pytest"]
