name: Content Resolver CI

on:
  #The workflow is triggered on push or pull request events for master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    container: 
      image: registry.fedoraproject.org/fedora:33
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update GPG keys
      run: dnf -y update fedora-gpg-keys

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install git and Python libraries
      run: dnf -y install git-core python3-yaml python3-jinja2 python3-pytest python3-flake8
    
    - name: Clean up
      run: dnf clean all
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        pytest
