name: Content Resolver CI

on:
  #The workflow is triggered on push or pull request events for master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-test --tag content-resolver-test:$(date +%s)
    - name: Run tests
      run: docker run pytest
